name: Pull Request Stats
on:
  pull_request:
    types: [ opened ]
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repositories: 'in2workspace/in2-desmos-api'
#          organization: 'in2workspace'
          period: 7
          charts: true
          disableLinks: true
          sortBy: 'COMMENTS'
          publishAs: 'DESCRIPTION'
